"""Initial migration

Revision ID: 7bc92180036c
Revises: 
Create Date: 2025-09-27 10:25:44.165648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bc92180036c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.alter_column('file_path',
               existing_type=sa.TEXT(),
               type_=sa.String(length=512),
               existing_nullable=True)
        batch_op.alter_column('file_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('file_mime',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_chat_message_is_read'))
        batch_op.drop_index(batch_op.f('idx_chat_message_sender'))

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_order_created_at'))
        batch_op.drop_index(batch_op.f('idx_order_is_paid'))
        batch_op.drop_index(batch_op.f('idx_order_paid_at'))
        batch_op.drop_index(batch_op.f('idx_order_status'))

    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_order_item_order_id'))
        batch_op.drop_index(batch_op.f('idx_order_item_product_id'))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_product_pinned'))
        batch_op.drop_index(batch_op.f('idx_product_status'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('username',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_product_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_product_pinned'), ['pinned'], unique=False)

    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_order_item_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_order_item_order_id'), ['order_id'], unique=False)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_order_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_order_paid_at'), ['paid_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_order_is_paid'), ['is_paid'], unique=False)
        batch_op.create_index(batch_op.f('idx_order_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_chat_message_sender'), ['sender'], unique=False)
        batch_op.create_index(batch_op.f('idx_chat_message_is_read'), ['is_read_by_admin'], unique=False)
        batch_op.alter_column('file_mime',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('file_name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('file_path',
               existing_type=sa.String(length=512),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
